repos:
  - repo: local
    hooks:
      - id: dune-build-fmt
        name: dune build @fmt
        entry: opam exec -- dune build @fmt --auto-promote
        pass_filenames: false
        language: system
        types: [text]
      - id: ocp-indent
        name: ocp-indent
        entry: opam exec -- ocp-indent --inplace
        language: system
        files: '.+\.mli?$'
        types: [text]
      # because seems like `dune build @fmt` doesn't regen the .opam file
      - id: dune-build
        name: dune build
        entry: opam exec -- dune build
        pass_filenames: false
        language: system
        types: [text]
